### ISSUE TITLE
Keon + PowerBlow Attachment (suction)

### ISSUE THREAD

**Issue by TheEternalDarkness** [Sauceke/LoveMachine#177] opened 2024-09-12 20:27 UTC
> What is an example of this type of device? (Provide link to iostindex.com entry or product page.)

The Keon (already supported) by Kiiroo is a stroker with positional output.  There is an attachment that can be linked to the Keon and is available on Kiiroo strokers (not the Keon but the actual stroker sleeves) that can replicate 'suction' behavior, called the PowerBlow.  It is capable of directly linking to the Keon and I'm not sure if it is accessible by the Keon by the underlying software or if it's separately connected, but that would need some research.

According to the buttplug.io website (underlying software compat level for Intiface Central), all Kiiroo products are supported. I haven't checked the list yet to see if this is available (the iostindex says "no" but last week Intiface Central was updated and has underlying buttplug.io support and three months of equipment IDs and new support added).

Would be nice to have this so you can have more of a 'full experience'.

> Do you volunteer to test this feature if it gets implemented? (I take no responsibility for accidents.)

Yes

**Comment by Sauceke** [comment] 2024-09-12 21:47
This is being [actively worked on](https://github.com/buttplugio/buttplug/issues/578) in Buttplug, which I guess means it's not ready yet.

**Comment by Sauceke** [comment] 2024-09-15 18:14
Closing as duplicate of #143

**Closed as not planned by Sauceke** 2024-09-15 18:14 UTC
Labels: duplicate
