### ISSUE TITLE
Lovense Solace Support

### ISSUE THREAD

**Issue by Nyanotech7820** [Sauceke/LoveMachine#155] opened 2023-11-23 23:55 UTC
Hi, would you be able to add support for the Lovense Solace? I tried using it in Holy Knight Ricca but got the "device not supported" warning. (Sorry, I know it just came out and so it might be too early to ask but I can do my best to test it in multiple different games)

![image_2023-11-23_185317549](https://github.com/Sauceke/LoveMachine/assets/57084368/f205e85a-1093-458d-af73-f2bce9a94e6a)

> What is an example of this type of device? (Provide link to iostindex.com entry or product page.)

https://www.lovense.com/solace-automatic-hands-free-male-masturbator?_utm_pro=2311121029&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJEhx80peuQfIq1v4Js0awcF3i-O5dDT5vHwF8tfZ_mwaULkcoZer2xoChOIQAvD_BwE

> Do you volunteer to test this feature if it gets implemented? (I take no responsibility for accidents.)

Yes I can test this feature in any of the compatible games I can get my hands on (currently have Holy night Ricca and VR Kanojo but I can get any others)

**Comment by Sauceke** [comment] 2023-11-25 09:43
dupe of #136

**Comment by dravpin** [comment] 2024-02-20 21:54
> dupe of #136

What do you mean dupe? the device in that post is a different device Please add lovense solace support when i connect everything it just says device not supported and does nothing

**Comment by Sauceke** [comment] 2024-02-20 22:04
@dravpin They are the same device type in Buttplug. When I add oscillator support, both of them will be automatically supported.

**Comment by dravpin** [comment] 2024-02-20 22:24
> @dravpin They are the same device type in Buttplug. When I add oscillator support, both of them will be automatically supported.

Oh i see interesting i didnt know that any ETA? i just bought my solace in the hopes of playing games with it boo womp

**Comment by Sauceke** [comment] 2024-02-22 12:33
Time for human trials.
https://github.com/Sauceke/LoveMachine/actions/runs/8004375296/artifacts/1266285999
Installer's in the ZIP.
You'll need to calibrate the Maximum RPM setting. The Test button should help with that. I'm curious if Speed Mixing works as intended, it should match the speed somewhat more precisely.

**Comment by dravpin** [comment] 2024-02-22 16:32
> Time for human trials. https://github.com/Sauceke/LoveMachine/actions/runs/8004375296/artifacts/1266285999 Installer's in the ZIP. You'll need to calibrate the Maximum RPM setting. The Test button should help with that. I'm curious if Speed Mixing works as intended, it should match the speed somewhat more precisely.

It seems to work well only problem is that once it starts it doesnt stop it just slows down intiface centrals lowest is the same thing is there anyway to set the lowest speed to 0 so that it stops when nothings happening?

**Comment by Sauceke** [comment] 2024-02-22 18:21
@dravpin That is a known bug in Buttplug/Intiface, will be fixed soon.

How accurate is the speed?

**Comment by dravpin** [comment] 2024-02-22 19:00
Oh i see good to know thank you!

**Comment by dravpin** [comment] 2024-02-22 20:41
> @dravpin That is a known bug in Buttplug/Intiface, will be fixed soon.
> 
> How accurate is the speed?

Very very inaccurate like way to fast although i suspect that has to do with the other problem i mentioned i can try getting a video if you would like

**Comment by Sauceke** [comment] 2024-02-22 20:59
@dravpin Have you tried decreasing the Maximum RPM setting

**Comment by Sauceke** [comment] 2024-02-22 21:13
Or rather, increasing it
Point is, you need to calibrate it bc every toy has a different top speed

**Comment by Nyanotech7820** [comment] 2024-02-23 13:15
Should hopefully be able to test the solace tonight with the plugin and I'll let you know how it goes. Aside from the intiface not stopping bug, any specific list of items or games you want me to test on top of the speed calibration or just try to break the plugin?

**Comment by Sauceke** [comment] 2024-02-23 14:27
@Nyanotech7820 You can test in any game, it's the same behavior in all of them.
I mainly want to know how well it can match slower speeds if the max rpm is set correctly, and whether it needs improvement.
Also if you have any other suggestions as to how to make it better.

**Comment by dravpin** [comment] 2024-02-23 21:07
> @dravpin Have you tried decreasing the Maximum RPM setting

how do i know what the maximum rpm is? the website says 280 strokes per minute i tried setting it to that but it didnt help anything be more accurate the problem is it going faster then the animation is

**Comment by Sauceke** [comment] 2024-02-23 21:29
@dravpin If it's too fast even with the correct rpm setting, that sounds like it could be the same reason it never fully stops. Maybe the bottom of the speed range is just missing from the buttplug impl. In that case you'll prolly have to wait until the fix is pushed in buttplug.

**Comment by Nyanotech7820** [comment] 2024-02-24 12:14
Update: 
Got to try the solace with AGH last night and tested it through a majority of the scenes and it seems to be doing pretty well, the speed is usually pretty close to the in game speed, but the difference is greatest at the highest and slowest speeds in game but I think that may be an issue with the capability of the solace moreso than the plugin. 

With the price you're paying for it I would have liked to maybe see a servo motor in the solace so we can actually sync to games, media, and other toys properly based on absolute positioning rather than estimated rpm but I know that would never happen lol.

**Comment by Sauceke** [comment] 2024-02-25 17:54
Added some new features so we can find out which ones to keep.
Let's move this conversation to #161.

**Closed as completed** 2024-04-28 15:48 UTC
Labels: duplicate
